---
- name: Copy custom Flannel YAML to target nodes
  ansible.builtin.copy:
    src: /home/sysadmin/kubernetes_network/kube-flannel.yml
    dest: /home/sysadmin/kube-flannel.yml
    mode: '0644'

- name: Install Flannel network plugin
  ansible.builtin.shell: su - $ANSIBLE_USER -c "kubectl apply -f /home/sysadmin/kube-flannel.yml"

- name: Taint master node to prevent workload scheduling
  ansible.builtin.shell: su - $ANSIBLE_USER -c "kubectl taint nodes --all node-role.kubernetes.io/control-plane-"
